
    <head>
        <link rel="stylesheet" type="text/css" href="_css/footer.css"/>
        <script type="text/javascript" src="_JavaScript/Linkfoto.js"></script>
    </head>
            <footer id="rp">
                    <address id="contato">
                        e-mail: luisitb@ig.com.br<br>
                        Telefone: (64) 8455-5397 <abbr title="Operadora oi"><q>oi</q></abbr><br>
                        Telefone: (64) 9206-8886 <abbr title="Operadora Claro"><q>claro</q></abbr><br>
                        Telefone: (64) 3404-4523 <abbr title="Telefone fixo Operadora CTBC "><q>ctbc</q></abbr>
                    </address>
                    <div id="desc">
                            Copyright &copy; 2015 <abbr title="Luís Carlos Da Silva Santos">Luís Carlos</abbr> 
                        <div id="ft">
                            <a class="icone" href="http://facebook.com" target="_blank">Facebook</a>  |
                            <a class="icone" href="http://twitter.com" target="_blank">Twitter</a> 
                        </div>
                    </div>
            </footer>
    </body>
</html>
