<?php
    /*require_once 'connect.php';
    
    try {
    $dbh = Cookbook::connect();
    print('<p>Connectado!!!</p>');
} catch (PDOException $ex) {
    print('<p>Não pode conectar para servidor!!!</p>');
    print('<p>Codigo erro: ' . $ex->getCode() . '</p>');
    print('<p>Mensagem erro: ' . $ex->getMessage() . '</p>');
    exit(1);
}
$dbh = NULL;
unset($dbh);
print('<p>Desconectado!!!</p>');*/
?>

<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Pagina Inicial</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="_css/header.css"/>
    </head>
    <body>
            <header id="cabpag"></header>                     