
    <head>
        <link rel="stylesheet" type="text/css" href="_css/menu.css"/>
    </head>
  
        <nav>
            <ul>
                <li> <a href="Home.php"> Home </a> <span> &shortmid; </span></li>
                <li> <a href="Servicos.php"> Serviços </a> <span> &shortmid; </span></li>
                <li> <a href="Dicas.php"> Dicas </a> <span> &shortmid; </span></li>
                <li> <a href="Download.php"> Download </a> <span> &shortmid; </span></li>
                <li> <a href="Contato.php"> Contato </a> <span> &shortmid; </span></li>
                <li id="login"> <a href="#"> Log In </a> <span> &shortmid; </span> &nbsp;</li>
                <li>
                    <form method="get" action="#">
                        <label for="search"> Search:&nbsp;</label>
                        <input type="search" id="search" name="search">&nbsp;&nbsp;
                        <input id="botao" type="submit" name="find" value="Enviar">&nbsp;&nbsp;
                    </form>
                </li>
            </ul>
        </nav>