<?php

$title = 'Delete album';
$url = $this->url('album', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($album->title) ?>" by
    "<?= $this->escapeHtml($album->artist) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
        <input type="submit" name="btn btn-danger" value="Yes" />
        <input type="submit" name="btn btn-success" value="No" />
    </div>
</form>