<html>
    <body>
        <!-- page footer -->

        <table style="width:100%; background-color:black; padding:12px; border:0px">
            <tr>
                <td>
                    <p class="foot">&copy; TLA Consulting Pty LTD.</p>
                    <p class="foot">Please see our <a href="valida.php">valida information page</a></p>
                </td>
            </tr>
        </table>
    </body>
</html>