<html>
    <head>
        <title>TLA Consulting Pty LTD</title>
        <style>
            h1{color:white; font-size: 24pt; text-align:center; font-family:arial, sans-serif}

            .menu {color:white; font-size:12pt; text-align:center; font-family:arial,sans-serif; font-weight:bold}

            td {background:black}

            p{color:black; font-size:12pt; text-align:justify; font-family:arial, sans-serif}

            p.foot {color:white; font-size:9pt; text-align:center; font-family:arial, sans-serif; font-weight:bold}

            a:link,a:visited,a:active {color:white}

        </style>
    </head>
    <body>

        <!-- page header -->

        <table style="width:100%; padding:12px; border:0px">
            <tr style="background-color:black">
                <td style="text-align: left"><img src="logoa.gif" alt="logo"></td>
                <td>
                    <h1>TLA Consulting</h1>
                </td>
                <td style="text-align: right"><img src="logob.gif" alt="logo"></td>
            </tr>
        </table>

        <!-- menu -->

        <table style="width:100%; background-color:white; padding:4px">
            <tr>
                <td style="width:25%">
                    <img src="loga.gif" alt="logo"><span class="menu"><a href="Home.php">Home</a></span></td>
                <td style="width:25%">
                    <img src="logb.gif" alt="logo"><span class="menu"><a href="vieworders.php">vieworders</a></span></td>
                <td style="width:25%">
                    <img src="loga.gif" alt="logo"><span class="menu"><a href="services.php">Services</a></span></td>
                <td style="width:25%">
                    <img src="logb.gif" alt="logo"><span class="menu"><a href="bobs_front_page.php">bobs_front_page</a></span></td>
            </tr>
        </table>
    </body>
</html>